1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
394: eth0@if395: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:ac:64:64:0a brd ff:ff:ff:ff:ff:ff link-netnsid 0
397: eth1@if396: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default 
    link/ether aa:c1:ab:af:ec:20 brd ff:ff:ff:ff:ff:ff link-netnsid 0
399: eth2@if398: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default 
    link/ether aa:c1:ab:23:90:2b brd ff:ff:ff:ff:ff:ff link-netnsid 0
